debug: false
dependencies:
  repositories:
    1:
      id: central
      url: https://repo1.maven.org/maven2
    2:
      id: wolfyscript
      url: https://maven.wolfyscript.com/repository/public/
  artifacts:
    1:
      groupId: com.wolfyscript.wolfyutils.spigot
      artifactId: wolfyutils-spigot
      version: 4.16.1.0
      scope: compile
jdbc:
  block_max_length: 1024
