name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]
  pull_request:
    types:
      - closed
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
          server-id: trqhxrd
          server-username: M2_USERNAME
          server-password: M2_PASSWORD
      - name: Build with Gradle
        run: ./gradlew build
      # - name: Deploy with Maven
      #   run: mvn -B deploy --file pom.xml
      #   env:
      #     M2_USERNAME: ${{ secrets.M2_USERNAME }}
      #     M2_PASSWORD: ${{ secrets.M2_PASSWORD }}
